id: P7E3BC377
initial_creation_type: input
source_metadata:
  title: Jetsün Mingyur Paldrön
  language: bo
  description: 'Texts by and about Jetsün Mingyur Paldrön (rje btsun mi ''gyur dpal
    sgron, 1699–1769), daughter of Minling Terchen Gyurme Dorje:'
  volume:
    3dba42ac97cc4c58935e72888cec9e8b:
      title: Mindrolling Lineage Prayer
      parent: Lineage Prayers
created_at: '2022-03-01T00:01:59.904692'
last_modified_at: '2022-03-01T00:01:59.904695'
statistics:
  total_words: 138
  total_non_words: 5
quality:
  non_words_ratio: 0.04
